from .Gemini_node import NODE_CLASS_MAPPINGS as GEMINI_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GEMINI_DISPLAY
from .Clip_batch_autoprompt import NODE_CLASS_MAPPINGS as CLIP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CLIP_DISPLAY

NODE_CLASS_MAPPINGS = {
    **GEMINI_MAPPINGS,
    **CLIP_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **GEMINI_DISPLAY,
    **CLIP_DISPLAY,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
