from .Gemini_node import NODE_CLASS_MAPPINGS as GEMINI_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GEMINI_DISPLAY
from .Clip_batch_autoprompt import NODE_CLASS_MAPPINGS as CLIP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CLIP_DISPLAY
from .batch_utils import NODE_CLASS_MAPPINGS as BATCH_UTILS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BATCH_UTILS_DISPLAY
from .nova_nodes_batch import NODE_CLASS_MAPPINGS as NOVA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as NOVA_DISPLAY
from .controlnet_batch_node import NODE_CLASS_MAPPINGS as CONTROLNET_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONTROLNET_DISPLAY
from .string_concat_batch import NODE_CLASS_MAPPINGS as STRING_CONCAT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STRING_CONCAT_DISPLAY
from .dataset_save import NODE_CLASS_MAPPINGS as DATASET_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DATASET_DISPLAY
from .human_review_node import NODE_CLASS_MAPPINGS as HUMAN_REVIEW_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as HUMAN_REVIEW_DISPLAY
from .gemini_moodboard_analyzer import NODE_CLASS_MAPPINGS as MOODBOARD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MOODBOARD_DISPLAY
from .gemini_carousel_pose_inventor import NODE_CLASS_MAPPINGS as POSE_INVENTOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as POSE_INVENTOR_DISPLAY

NODE_CLASS_MAPPINGS = {
    **GEMINI_MAPPINGS,
    **CLIP_MAPPINGS,
    **BATCH_UTILS_MAPPINGS,
    **NOVA_MAPPINGS,
    **CONTROLNET_MAPPINGS,
    **STRING_CONCAT_MAPPINGS,
    **DATASET_MAPPINGS,
    **HUMAN_REVIEW_MAPPINGS,
    **MOODBOARD_MAPPINGS,
    **POSE_INVENTOR_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **GEMINI_DISPLAY,
    **CLIP_DISPLAY,
    **BATCH_UTILS_DISPLAY,
    **NOVA_DISPLAY,
    **CONTROLNET_DISPLAY,
    **STRING_CONCAT_DISPLAY,
    **DATASET_DISPLAY,
    **HUMAN_REVIEW_DISPLAY,
    **MOODBOARD_DISPLAY,
    **POSE_INVENTOR_DISPLAY,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
